### ISSUE TITLE
Please provide AppImage file unzipped for download

### ISSUE THREAD

**Issue by probonopd** [genesis-lab-team/minter-autodelegator#1]
Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

Thank you.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by i7495** [comment]
Thanks for the info. We will not put AppImage into archives in the next releases.
